### ISSUE TITLE
Add `todoFilePath` to todoData

### ISSUE THREAD

**Issue by scalvert** [ember-template-lint/ember-template-lint-todo-utils#15]
We should add the path to the todo file in order to simplify deletion (we won't need to regenerate the filePath using the todo data contents).

**Comment by rwjblue** [comment]
This seems fine, but we need to be very careful about how we implement or we will make the contents unstable across various checkouts (e.g. different folks check things out to different locations leading to different paths).

**Comment by scalvert** [comment]
@rwjblue and I discussed in person and decided we'd avoid adding this to the file to keep the contents stable.
