### ISSUE TITLE
Export typescript types publicly

### ISSUE THREAD

**Issue by renatoi** [ember-template-lint/ember-template-lint-todo-utils#18]
Addons that depend on this lib may need to import typescript types. Currently they need to dig into a private module like so:

```typescript
import { TodoData } from '@ember-template-lint/todo-utils/lib/types';
```

Ideally we want lib authors to use it like this:

```typescript
import { TodoData } from '@ember-template-lint/todo-utils';
```

**Comment by rwjblue** [comment]
Ya, we should export the types from our entry point for anything that is actually going to be needed when interacting with our public APIs.

**Comment by scalvert** [comment]
Yep, agree. This was just an oversight.

**Comment by scalvert** [comment]
Actually, they are exported. Perhaps reference the latest code, @renatoi?

https://github.com/ember-template-lint/ember-template-lint-todo-utils/blob/master/src/index.ts#L14

**Comment by renatoi** [comment]
Yes it works. Thanks!
