### ISSUE TITLE
Request: add way to group todo output by violation

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint-todo-utils#217]
Right now, there's not a good way for users to figure out what linting violation to fix first. A team might want to fix a single rule across the whole code base, instead of fixing file-by-file.

It would be a nice DX to have an output that grouped by rule, or perhaps a quick summary that listed rules that were being violated and their count.

**Comment by elwayman02** [comment]
To add a bit more concrete detail, there are two workflows we're interested in supporting for our template linting strategy once we have TODOs in place:

1) We want to generate a list of all rules that are being silenced by the TODOs. This would allow us to prioritize which rules to fix.
2) Once we've decided which rule we're going to work on fixing, we want to be able to output to the console all failures of that type, ideally in a similar format to how they're displayed without TODOs (listing the file and outputting the line where the error occurs). This would allow us to work through the errors one by one and use that output to know when all failures of that type have been addressed.

**Comment by scalvert** [comment]
So this isn't really a feature that'd be implemented in this library itself. This would be something that would be implemented in one of the consuming libraries (`@scalvert/eslint-formatter-todo` or `ember-template-lint`), as those libraries are responsible for how todos are used and output.

That said, it's possible to output todos ordered by due date desc. It would be a slightly different implementation for both, but we could keep them relatively in sync.

**Comment by scalvert** [comment]
I'm going to close this in favor of opening issues in the respective consuming repositories.
