### ISSUE TITLE
Restructure `.lint-todo` directory contents

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-lint-todo-utils#8]
Currently, we have a single flat `.lint-todo` folder structure where all of the todo items are in that directory directly. This means that to check todo for a single file (e.g. your editor is running linting) we have to parse all of the `.lint-todo` folder contents which could be quite large.

I'd like to restructure things to be structured such that `.lint-todo` contains a folder per-file with todo items (that folder's name would be a hash of the full filename) as its contents. This would allow the most common operation (reading all todo items for a given file, or updating the todo items for a file) to be much quicker.

**Comment by scalvert** [comment]
Agree. Will do this ASAP.

**Comment by rwjblue** [comment]
@scalvert - I think this is done?

**Comment by scalvert** [comment]
This is in progress. I'll have a PR up soon.

**Comment by scalvert** [comment]
This is implemented. We just need to resolve #19. Going to close this as that issue tracks the remaining work.
